### ISSUE TITLE
Right eye bloom and Reflection Angles incorrect

### ISSUE THREAD

**Issue by YaBoi3K** [guppyexpress/PimaxLightFix#1]
(Pimax 5K+, Modded Beat Saber 1.18.3)

With this mod installed and parallel projections off, most lighting elements are displayed correctly. However, there are a few things that aren't:

Reflections/mirrors: The reflection angle (for lack of a better term) is incorrect. Looks the same as without this mod EXCEPT the right eye is aligned with the left eye instead of being cross-eyed. They converge, but are not in the correct place.

Bloom: Left eye is fine. Right eye looks incorrect, not sure how to better describe it.

Otherwise works as intended. Turning off Mirrors/reflections helps enormously. Turning off Bloom post-processing helps a little, but not fully.

**Comment by YaBoi3K** [comment]
Also tried unistalling all other mods. Didn't fix the issue.

**Comment by guppyexpress** [comment]
Hello! 

reflections/mirrors, and the bloom i am currently working on getting corrected, i was slightly rushed for this part of the project and thus i had to just make it non cross eyed as a temporary fix. the bloom and reflection will be fixed in a later update. thank you for alerting me again about this. but at the moment the reflections and bloom are not cross eyed. i will fix it soon

**Comment by YaBoi3K** [comment]
Nah I get it. You seem busy with the Eye tracking stuff. I'd totally help with maintaining this if I knew what I was doing, though I don't have any experience with making Beat Saber Mods.

**Comment by guppyexpress** [comment]
haha yeah, i have been working on fixing the Eye Tracking for Pimax headsets because it doesnt work.
